version: '3'
services:
  the-internet:
    image: gprestes/the-internet
    ports:
      - '5000:5000'
    networks:
      - net
  jenkins:
    image: "jenkins/jenkins:lts"
    container_name: "jenkins_new"
    volumes:
        - "./jenkins_home/:/var/jenkins_home"
        - /var/run/docker.sock:/var/run/docker.sock:rw
        - /usr/bin/docker:/usr/bin/docker
    ports:
        - 8080:8080
    networks:
        - net
networks:
  net:
      
      